"""Generate an OpenRig rig from an antkeeper handlers file.

The rig has two pods:

* ``orch`` — one orchestrator seat (``lead``) that starts workflows and
  reports their outcome. It carries one skill per workflow, so the user can
  type e.g. ``/sdlc add dark mode`` in its terminal.
* ``steps`` — one seat per antkeeper step, named after the step.

Each registered handler becomes an OpenRig workflow spec under
``.openrig/workflows``. The workflow runtime moves a packet from step seat to
step seat. Antkeeper's state dict travels with the packets: each step hands off
with a ``{"summary", "state"}`` JSON result note, which the runtime copies into
the next packet. Every workflow ends at the orchestrator's ``close`` step; a
failed step raises a workflow exception to the orchestrator, which resumes it.
"""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from antkeeper.loader import load_module
from antkeeper.openrig.introspect import GenerationError, HandlersSpec, Step, Workflow, introspect

LEAD_POD = "orch"
LEAD_MEMBER = "lead"
STEPS_POD = "steps"
ORCHESTRATOR = "orchestrator"
CLOSE_STEP = "close"
AGENTS_DIR = ".openrig/agents"
WORKFLOWS_DIR = ".openrig/workflows"
SHARED_DIR = ".openrig/shared"
GENERATED_MARKER = "<!-- Generated by `antkeeper generate-rig`. Regenerate instead of editing. -->"

_SHARED_PLUGINS = ["shared:openrig-core"]
_SHARED_RUNTIME_RESOURCES = [
    "shared:claude-default-settings",
    "shared:claude-default-mcp",
    "shared:codex-default-config",
    "shared:claude-activity-hooks",
]
# Seats coordinate through these rig subcommands; allowlisting them keeps
# workflow motion from stalling on permission prompts.
_RIG_SUBCOMMANDS = ["whoami", "queue", "workflow", "capture", "send", "ps", "transcript"]
_RIG_PERMISSIONS = "runtime/claude-rig-permissions.fragment.json"
# How a step seat works out its input state. State travels in the workflow
# runtime as one JSON object, {"summary": ..., "state": ...}, mirroring
# antkeeper's Runner, which adds run_id and workflow_name to every run.
_INPUT_STATE_RULE = """\
- Handoff packet: the `Prior step note` is a JSON object. Its `state` is your input.
- Resume packet: the `decision` is a JSON object. Its `state` is your input. If the
  decision carries no state, exit `failed` with the note "resume carried no state";
  the orchestrator resumes again with it. Do not guess.
- First step: use the `Root objective`. If it is a JSON object, it is the initial
  state (or its `state` value, if it has one). Any other text becomes
  `{"prompt": "<root objective>"}`.
- Then set `run_id` to the workflow instance id and `workflow_name` to the
  workflow id, both from the packet header, as antkeeper does."""
_STATE_NOTE = '{"summary": "<one line: what you did>", "state": {<input state plus your outputs>}}'
_ORCHESTRATOR_SKILLS = ["orchestration-team", "verification-before-completion"]
_STEP_SKILLS = ["systematic-debugging", "verification-before-completion"]


@dataclass
class GeneratedRig:
    """Outcome of a rig generation.

    Attributes:
        rig_name: Name of the generated rig.
        lead_session: Session address of the orchestrator seat.
        files: Paths written, relative to the output directory.
        launchers: Workflow skill names, keyed by workflow name.
        warnings: Notes about parts of the handlers file that translate approximately.
        shared_copied: Whether the OpenRig shared agent pool was copied in.
    """

    rig_name: str
    lead_session: str
    files: list[str] = field(default_factory=list)
    launchers: dict[str, str] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)
    shared_copied: bool = False


def generate_rig(
    handlers_file: str,
    output_dir: str = ".",
    *,
    rig_name: str | None = None,
    force: bool = False,
    shared_source: Path | None = None,
) -> GeneratedRig:
    """Generate an OpenRig rig for the handlers file into ``output_dir``.

    Args:
        handlers_file: Path to the antkeeper handlers file.
        output_dir: Project root that receives ``rig.yaml``, ``CULTURE.md`` and
            ``.openrig/``. Seats work in this directory.
        rig_name: Rig name; defaults to the output directory name.
        force: Overwrite files that already exist.
        shared_source: OpenRig's shared agent spec directory, copied to
            ``.openrig/shared`` when the project does not have one. Defaults to
            the copy shipped with the installed ``rig`` CLI.

    Returns:
        A summary of what was generated.

    Raises:
        GenerationError: If the handlers file cannot be loaded or translated,
            files would be overwritten without ``force``, or no shared agent
            pool is available.
    """
    out = Path(output_dir).resolve()
    if not out.is_dir():
        raise GenerationError(f"output directory does not exist: {out}")
    try:
        module = load_module(handlers_file)
    except FileNotFoundError as error:
        raise GenerationError(f"handlers file not found: {handlers_file}") from error
    spec = introspect(module)

    name = _rig_name(rig_name or out.name)
    handlers_path = Path(handlers_file).resolve()
    handlers_ref = handlers_path.relative_to(out).as_posix() if handlers_path.is_relative_to(out) else handlers_path.name
    rendered = _Renderer(spec, name, handlers_ref, _taken_commands(spec, out))
    files = rendered.files()

    if not force:
        existing = sorted(path for path in files if (out / path).exists())
        if existing:
            raise GenerationError("refusing to overwrite (use --force): " + ", ".join(existing))

    shared_target = out / SHARED_DIR
    copy_shared = not (shared_target / "agent.yaml").is_file()
    if copy_shared:
        source = shared_source or find_openrig_shared()
        if source is None:
            raise GenerationError(
                f"{SHARED_DIR} is missing and the OpenRig CLI (`rig`) was not found to copy it from; install OpenRig first"
            )
        shutil.copytree(source, shared_target, dirs_exist_ok=True)

    for path, content in files.items():
        target = out / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)

    return GeneratedRig(
        rig_name=name,
        lead_session=rendered.lead_session,
        files=list(files),
        launchers=rendered.launchers,
        warnings=rendered.warnings,
        shared_copied=copy_shared,
    )


def find_openrig_shared() -> Path | None:
    """Locate the shared agent spec pool shipped with the installed ``rig`` CLI.

    Returns:
        The ``daemon/specs/agents/shared`` directory of the OpenRig package, or
        ``None`` when ``rig`` is not on ``PATH``.
    """
    rig = shutil.which("rig")
    if rig is None:
        return None
    for parent in Path(rig).resolve().parents:
        candidate = parent / "daemon" / "specs" / "agents" / "shared"
        if (candidate / "agent.yaml").is_file():
            return candidate
    return None


def session(pod: str, member: str, rig: str) -> str:
    """Return the canonical OpenRig session address of a seat."""
    return f"{pod}-{member}@{rig}"


def _rig_name(name: str) -> str:
    """Normalise a rig name to lowercase letters, digits, ``_`` and ``-``."""
    slug = re.sub(r"[^a-z0-9_-]+", "-", name.lower()).strip("-_")
    if not slug:
        raise GenerationError(f"cannot derive a rig name from {name!r}; pass --name")
    return slug


def _skill_name(workflow: str) -> str:
    """Convert a workflow name into a skill name (lowercase, hyphenated)."""
    return re.sub(r"[^a-z0-9]+", "-", workflow.lower()).strip("-")


def _taken_commands(spec: HandlersSpec, out: Path) -> set[str]:
    """Slash command names a workflow skill must not shadow.

    These are the commands the steps themselves run, plus the project's own
    commands and skills, excluding skills this generator projected earlier.
    """
    taken = {step.command.lstrip("/") for step in spec.steps.values() if step.command}
    commands = out / ".claude" / "commands"
    if commands.is_dir():
        taken |= {":".join(p.relative_to(commands).with_suffix("").parts) for p in commands.rglob("*.md")}
    skills = out / ".claude" / "skills"
    if skills.is_dir():
        for skill in skills.glob("*/SKILL.md"):
            if GENERATED_MARKER not in skill.read_text():
                taken.add(skill.parent.name)
    return taken


class _Renderer:
    """Renders every generated file for one rig."""

    def __init__(self, spec: HandlersSpec, rig: str, handlers_ref: str, taken_commands: set[str]) -> None:
        self.spec = spec
        self.rig = rig
        self.handlers_ref = handlers_ref
        self.lead_session = session(LEAD_POD, LEAD_MEMBER, rig)
        self.warnings: list[str] = [f"skipped {reason}" for reason in spec.skipped.values()]
        self.launchers: dict[str, str] = {}
        for wf in spec.workflows.values():
            skill = _skill_name(wf.name)
            if not skill or skill in taken_commands:
                self.warnings.append(
                    f"workflow {wf.name!r}: no /{skill} skill (the name is already a slash command); ask the orchestrator to run it"
                )
            else:
                self.launchers[wf.name] = skill
            if wf.glue_source:
                self.warnings.append(
                    f"workflow {wf.name!r} has logic beyond its steps; the orchestrator is shown its source but steps run in sequence"
                )

    def step_session(self, step: Step) -> str:
        return session(STEPS_POD, step.seat, self.rig)

    def files(self) -> dict[str, str]:
        """Return generated file contents keyed by path relative to the output directory."""
        files = {
            "rig.yaml": _yaml(self.rig_spec()),
            "CULTURE.md": self.culture(),
        }
        orchestrator = f"{AGENTS_DIR}/{ORCHESTRATOR}"
        files[f"{orchestrator}/agent.yaml"] = _yaml(_agent_spec(
            ORCHESTRATOR,
            f"Orchestrator for the antkeeper workflows in {self.handlers_ref}",
            _ORCHESTRATOR_SKILLS,
            local_skills=list(self.launchers.values()),
        ))
        files[f"{orchestrator}/{_RIG_PERMISSIONS}"] = _RIG_PERMISSIONS_JSON
        files[f"{orchestrator}/guidance/role.md"] = self.orchestrator_role()
        files[f"{orchestrator}/startup/context.md"] = self.orchestrator_context()
        for wf_name, skill in self.launchers.items():
            files[f"{orchestrator}/skills/{skill}/SKILL.md"] = self.launcher_skill(self.spec.workflows[wf_name], skill)
        for step in self.spec.steps.values():
            base = f"{AGENTS_DIR}/{step.seat}"
            files[f"{base}/agent.yaml"] = _yaml(_agent_spec(
                step.seat, f"Antkeeper step `{step.name}`: {step.summary}", _STEP_SKILLS, local_skills=[]
            ))
            files[f"{base}/{_RIG_PERMISSIONS}"] = _RIG_PERMISSIONS_JSON
            files[f"{base}/guidance/role.md"] = self.step_role(step)
            files[f"{base}/startup/context.md"] = self.step_context(step)
        for wf in self.spec.workflows.values():
            files[f"{WORKFLOWS_DIR}/{wf.name}.yaml"] = _yaml(self.workflow_spec(wf))
        return files

    # -- rig and workflow specs ----------------------------------------------

    def rig_spec(self) -> dict[str, Any]:
        steps = list(self.spec.steps.values())
        step_members = []
        for step in steps:
            member: dict[str, Any] = {
                "id": step.seat,
                "agent_ref": f"local:{AGENTS_DIR}/{step.seat}",
                "profile": "default",
                "runtime": "claude-code",
                "cwd": ".",
            }
            if step.model:
                member["model"] = step.model
            step_members.append(member)
        return {
            "version": "0.2",
            "name": self.rig,
            "summary": (
                f"Generated by antkeeper generate-rig from {self.handlers_ref}. The orchestrator "
                "starts antkeeper workflows; each step runs on its own seat."
            ),
            "culture_file": "CULTURE.md",
            "managed_blocks": {"claude-code": "CLAUDE.local.md"},
            "pods": [
                {
                    "id": LEAD_POD,
                    "label": "Orchestration",
                    "summary": "Starts workflows and reports their outcome.",
                    "members": [{
                        "id": LEAD_MEMBER,
                        "agent_ref": f"local:{AGENTS_DIR}/{ORCHESTRATOR}",
                        "profile": "default",
                        "runtime": "claude-code",
                        "cwd": ".",
                    }],
                    "edges": [],
                },
                {
                    "id": STEPS_POD,
                    "label": "Steps",
                    "summary": "One seat per antkeeper step, named after the step.",
                    "members": step_members,
                    "edges": [],
                },
            ],
            "edges": [
                {"kind": "delegates_to", "from": f"{LEAD_POD}.{LEAD_MEMBER}", "to": f"{STEPS_POD}.{step.seat}"}
                for step in steps
            ],
        }

    def workflow_spec(self, wf: Workflow) -> dict[str, Any]:
        steps = [self.spec.steps[name] for name in wf.steps]
        roles: dict[str, Any] = {
            ORCHESTRATOR: {"preferred_targets": [self.lead_session]},
        }
        for step in steps:
            roles[step.seat] = {"preferred_targets": [self.step_session(step)]}
        step_ids = _unique_ids([step.seat for step in steps])
        workflow_steps = [
            {
                "id": step_id,
                "actor_role": step.seat,
                "objective": (
                    f"Antkeeper step `{step.name}` ({index} of {len(steps)} in `{wf.name}`): {step.summary} "
                    f"Before acting, read {AGENTS_DIR}/{step.seat}/guidance/role.md; it is your current "
                    "instruction. Your input state is the JSON object in this packet."
                ),
                "allowed_exits": ["handoff", "waiting", "failed"],
            }
            for index, (step_id, step) in enumerate(zip(step_ids, steps), start=1)
        ]
        workflow_steps.append({
            "id": CLOSE_STEP,
            "actor_role": ORCHESTRATOR,
            "objective": (
                f"Read {AGENTS_DIR}/{ORCHESTRATOR}/guidance/role.md, then report the outcome of `{wf.name}` "
                "from the final state in the prior step note and exit done."
            ),
            "allowed_exits": ["done", "failed"],
            "next_hop": {"mode": "forbid"},
        })
        return {
            "workflow": {
                "id": wf.name,
                "version": 1,
                "objective": f"{wf.summary} (antkeeper handler `{wf.name}` in {self.handlers_ref})",
                "target": {"rig": self.rig},
                "entry": {"role": steps[0].seat},
                "coordination_terminal_turn_rule": "hot_potato",
                "exception_routing": {"default": ORCHESTRATOR, "orchestrator_role": ORCHESTRATOR},
                "roles": roles,
                "steps": workflow_steps,
                "loop_guards": {"max_hops": len(workflow_steps) + 2},
            }
        }

    # -- markdown ------------------------------------------------------------

    def culture(self) -> str:
        return f"""\
# {self.rig} culture

{GENERATED_MARKER}

This rig runs the antkeeper workflows defined in `{self.handlers_ref}`. Each antkeeper
step has its own seat, named after the step, and the orchestrator
(`{self.lead_session}`) starts workflows and reports their outcome.

## How work moves

- The user asks the orchestrator to run a workflow, usually with its skill
  (for example `/{next(iter(self.launchers.values()), "<workflow>")} <prompt>`).
- The orchestrator starts an OpenRig workflow instance from
  `{WORKFLOWS_DIR}/<workflow>.yaml`. The runtime hands a packet to the first step seat.
- Each step seat performs its step, then runs `rig workflow project`, which closes
  its packet and hands the next one to the next step.
- Every workflow ends at the orchestrator's `{CLOSE_STEP}` step, which reports back.
- A step that fails exits `failed`. The runtime raises a workflow exception to the
  orchestrator, and once the cause is fixed `rig workflow resume` re-runs that
  step. Completed steps never re-run.

## Workflow state

Antkeeper threads a state object through the steps. Here it travels with the work,
inside the workflow runtime. There is no state file.

- The first step builds it from the root objective. A JSON object is the initial
  state; any other text becomes `{{"prompt": "<text>"}}`. Every run also gets
  `run_id` (the workflow instance id) and `workflow_name`, as in antkeeper.
- Each step hands off with one JSON object as its result note:
  `{_STATE_NOTE}`. The state is the whole state so far, and a step never drops
  keys. The runtime copies the note into the next step's packet.
- `rig workflow show <id> --json` shows the latest state
  (`lastContinuationDecision.resultNote`), and the orchestrator receives the
  final state in its `{CLOSE_STEP}` packet.
- Read packets with `rig queue show <id> --full`. The default view truncates the
  body, which would cut the state JSON short.

## Principles

- Do your own step and only your own step. Workflow order belongs to the runtime.
- Handoffs are durable: use `rig workflow project`, not chat, to move work.
- Run `rig` commands on their own. They are allowlisted, but piping their output
  into `python3`, `jq` or other programs triggers an approval prompt that stalls
  the workflow. Read JSON output directly.
- Report failure honestly. Put the reason in the result note rather than guessing
  or papering over a gap.
- A step may publish (push, open a PR) only when its own instructions say so.
  Anything else outward-facing or destructive needs the user's authorization.
"""

    def orchestrator_role(self) -> str:
        workflow_rows = "\n".join(
            f"| `{wf.name}` | {f'`/{self.launchers[wf.name]}`' if wf.name in self.launchers else '—'} | "
            f"{' → '.join(f'`{name}`' for name in wf.steps)} | {_cell(wf.summary)} |"
            for wf in self.spec.workflows.values()
        )
        seat_rows = "\n".join(
            f"| `{step.name}` | `{self.step_session(step)}` | {_cell(step.summary)} |"
            for step in self.spec.steps.values()
        )
        return f"""\
# Role: Orchestrator

{GENERATED_MARKER}

You lead the `{self.rig}` rig, generated from the antkeeper handlers file
`{self.handlers_ref}`. You run antkeeper workflows by starting OpenRig workflow
instances. The step seats do the work; you start each run, watch it, and report
the outcome to the user.

## Starting a workflow

The user starts a workflow with its skill (for example
`/{next(iter(self.launchers.values()), "<workflow>")} add dark mode`) or by asking in words. In both cases:

1. The prompt is the user's request. If it names an existing file, use the file's
   contents, as `antkeeper run` does. To seed other state keys, as
   `antkeeper run --initial-state` does, pass a JSON object as the root objective
   instead, for example `{{"prompt": "...", "spec_file": "specs/x.md"}}`. A
   single-step workflow needs this when its step reads keys other than `prompt`.
2. Instantiate the workflow, passing the prompt as the root objective:

   ```bash
   rig workflow instantiate "$PWD/{WORKFLOWS_DIR}/<workflow>.yaml" \\
     --created-by {self.lead_session} --json \\
     --root-objective '<prompt>'
   ```

   Run it from the project root: the daemon resolves a relative spec path against its own
   directory, so the path must be absolute. Single-quote the prompt and write each `'`
   inside it as `'\\''`.

3. Tell the user the instance id and the step sequence. `rig workflow show <id>`
   and `rig workflow trace <id>` show progress.

## Closing a workflow

Every workflow ends with a `{CLOSE_STEP}` packet addressed to you. When it arrives:

1. Claim it and read it with `rig queue show <qitem-id> --full`. The `Prior step
   note` is a JSON object, and its `state` is the final state.
2. Report to the user: which steps ran, and the final state keys that matter (for
   example a PR URL or branch name).
3. Close the packet:

   ```bash
   rig workflow project --instance <id> --current-packet <qitem-id> \\
     --exit done --actor-session {self.lead_session} --result-note "<one-line outcome>"
   ```

## When a step fails

A failed step raises a `WORKFLOW EXCEPTION` queue item to you, and the instance
stops at that step. Read the reason, then find the state the step received:

1. In `rig workflow trace <id> --json`, take the latest trail entry for the failed
   step with closure reason `failed`. Its `priorQitemId` is the packet the step
   failed on.
2. Read that packet with `rig queue show <priorQitemId> --full`. The state is the
   JSON object in its `Prior step note`, or in its `decision` if it was itself a
   resume. If it was the first step, build the state from the `Root objective`
   as the step would.

Fix the cause, correcting the state if that is the problem, or ask the user to
decide. Then re-run the failed step, passing the state in the decision as one JSON
object (single-quoted, with each `'` written as `'\\''`):

```bash
rig workflow resume <id> --actor-session {self.lead_session} \\
  --decision '{{"summary": "<what changed>", "state": {{...}}}}'
```

Completed steps never re-run. If the run should not continue, tell the user and
leave the instance failed.

## Workflows

| Workflow | Skill | Steps | Purpose |
|---|---|---|---|
{workflow_rows}

## Step seats

| Step | Seat | Does |
|---|---|---|
{seat_rows}

## Boundaries

- Do not perform step work yourself; route it to the step's seat.
- If a step seat stalls, look at it (`rig capture <seat>`) and unblock it. A seat
  waiting on a permission prompt or a question needs the user's decision; ask
  for it plainly.
"""

    def orchestrator_context(self) -> str:
        seats = "\n".join(f"- `{step.name}`: `{self.step_session(step)}`" for step in self.spec.steps.values())
        return f"""\
# Startup Context

Run `rig whoami --json` before making topology claims. Confirm that your session
is `{self.lead_session}`.

Default workflow role: `{ORCHESTRATOR}` (start workflows, close them, own exceptions).

Step seats:

{seats}

Workflow specs live in `{WORKFLOWS_DIR}/`. Workflow state travels in packet notes;
see `CULTURE.md`.
"""

    def launcher_skill(self, wf: Workflow, skill: str) -> str:
        sequence = " → ".join(
            f"`{name}` ({self.step_session(self.spec.steps[name])})" for name in wf.steps
        )
        glue = ""
        if wf.glue_source:
            glue = f"""
## Handler logic beyond the steps

The antkeeper handler does more than run its steps in order. The rig runs only the
step sequence above, in this repository's working tree. Before you start, tell the
user what the extra logic below would have done and agree how to handle it, for
example by preparing a worktree or branch first.

```python
{wf.glue_source}
```
"""
        return f"""\
---
name: {skill}
description: >-
  Start the antkeeper `{wf.name}` workflow on this rig ({' -> '.join(wf.steps)}).
  Use when the user types /{skill} <prompt> or asks the orchestrator to run {wf.name}.
  For the orchestrator seat only.
---

{GENERATED_MARKER}

# {wf.name}

{wf.doc or wf.summary}

Steps: {sequence}, then `{CLOSE_STEP}` (you).

## Start it

1. The prompt is: $ARGUMENTS
   If it names an existing file, use the file's contents. If it is empty and the
   first step needs a prompt, ask the user what the workflow should work on. To
   seed other state keys, pass a JSON object instead (see your role).
2. Instantiate the workflow:

   ```bash
   rig workflow instantiate "$PWD/{WORKFLOWS_DIR}/{wf.name}.yaml" \\
     --created-by {self.lead_session} --json \\
     --root-objective '<prompt>'
   ```

   Run it from the project root: the daemon resolves a relative spec path against its own
   directory, so the path must be absolute. Single-quote the prompt and write each `'`
   inside it as `'\\''`.

3. Tell the user the instance id and the steps above. The `{CLOSE_STEP}` packet
   comes back to you when the steps finish; close it as your role describes.
{glue}"""

    def step_role(self, step: Step) -> str:
        used_by = ", ".join(f"`{wf.name}`" for wf in self.spec.workflows.values() if step.name in wf.steps)
        step_session = self.step_session(step)
        return f"""\
# Role: {step.name}

{GENERATED_MARKER}

You perform the antkeeper step `{step.name}` from `{self.handlers_ref}`, and only
that step, whenever a workflow hands it to you. {step.summary}

Re-read this file at the start of every packet. It may have been regenerated since
you started, and the current file is your instruction.

Workflows that use this step: {used_by}.

## The step

{step.instructions}

## Handling a workflow packet

Work arrives as a queue packet from the OpenRig workflow runtime.

1. Find it with `rig queue list --owned` and read it with
   `rig queue show <qitem-id> --full`. Always use `--full`: the default view
   truncates the body, which would cut the state JSON short.
2. Claim it: `rig queue claim <qitem-id>`.
3. Work out your input state from the packet:
{_indent(_INPUT_STATE_RULE, "   ")}
4. Perform the step above in this repository, resolving placeholders from the
   input state.
5. Hand off with the whole state, your outputs merged in, as one JSON object with
   `summary` first:

   ```bash
   rig workflow project --instance <workflow-instance-id> --current-packet <qitem-id> \\
     --exit handoff --actor-session {step_session} \\
     --result-note '{_STATE_NOTE}'
   ```

   Keep every key from the input state. Single-quote the note and write each `'`
   inside it as `'\\''`. Write the note directly; do not build it with `python3`
   or `jq`.

If the step cannot be completed, run the same command with `--exit failed` and a
plain-text result note that gives the reason. The runtime raises a workflow exception to the
orchestrator (`{self.lead_session}`), which re-runs this step with `rig workflow
resume` once the cause is fixed. Do not perform other steps, and do not start work
without a packet.
"""

    def step_context(self, step: Step) -> str:
        return f"""\
# Startup Context

Run `rig whoami --json` before making topology claims. Confirm that your session
is `{self.step_session(step)}`.

Default workflow role: `{step.seat}` (antkeeper step `{step.name}`).

Packets come from the workflow runtime. Hand off with `rig workflow project`; the
runtime chooses the next seat. Escalate anything the step cannot decide to the
orchestrator, `{self.lead_session}`.
"""


def _agent_spec(name: str, description: str, skills: list[str], *, local_skills: list[str]) -> dict[str, Any]:
    """Build an AgentSpec that imports OpenRig's shared pool, in the style of the shipped agents."""
    resources: dict[str, Any] = {
        "guidance": [
            {"id": "role", "path": "guidance/role.md"},
            {"id": "startup-context", "path": "startup/context.md"},
        ],
        "runtime_resources": [
            {"id": "rig-permissions", "path": _RIG_PERMISSIONS, "runtime": "claude-code", "type": "claude_settings_fragment"},
        ],
    }
    if local_skills:
        resources["skills"] = [{"id": skill, "path": f"skills/{skill}"} for skill in local_skills]
    return {
        "name": name,
        "version": "1.0",
        "description": description,
        "defaults": {"runtime": "claude-code"},
        "imports": [{"ref": "local:../../shared"}],
        "profiles": {
            "default": {
                "uses": {
                    "skills": [*skills, *local_skills],
                    "guidance": [],
                    "subagents": [],
                    "plugins": _SHARED_PLUGINS,
                    "runtime_resources": [*_SHARED_RUNTIME_RESOURCES, "rig-permissions"],
                }
            }
        },
        "resources": resources,
        "startup": {
            "files": [
                {"path": "guidance/role.md", "delivery_hint": "send_text", "required": True},
                {"path": "startup/context.md", "delivery_hint": "send_text", "required": True},
            ],
            "actions": [],
        },
    }


def _unique_ids(ids: list[str]) -> list[str]:
    """Suffix repeated ids (``implement``, ``implement-2``) so step ids are unique."""
    counts: dict[str, int] = {}
    unique = []
    for step_id in ids:
        counts[step_id] = counts.get(step_id, 0) + 1
        unique.append(step_id if counts[step_id] == 1 else f"{step_id}-{counts[step_id]}")
    return unique


def _indent(text: str, prefix: str) -> str:
    """Indent every line of text, e.g. to nest a list under a numbered step."""
    return "\n".join(prefix + line for line in text.splitlines())


def _cell(text: str) -> str:
    """Make text safe for a markdown table cell."""
    return " ".join(text.split()).replace("|", "\\|")


_RIG_PERMISSIONS_JSON = json.dumps(
    {"permissions": {"allow": [f"Bash(rig {command}:*)" for command in _RIG_SUBCOMMANDS]}}, indent=2
) + "\n"


class _Dumper(yaml.SafeDumper):
    """YAML dumper that writes multi-line strings as literal blocks and never emits aliases."""

    def ignore_aliases(self, data: Any) -> bool:
        return True


def _represent_str(dumper: yaml.SafeDumper, data: str) -> yaml.Node:
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_Dumper.add_representer(str, _represent_str)


def _yaml(data: dict[str, Any]) -> str:
    """Serialise a spec to YAML, preserving key order."""
    return yaml.dump(data, Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=100)
